#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Starting Network"
    for ifline in "${IF_UP[@]}"; do
      /sbin/ifconfig $ifline || stat_fail && exit 1
    done
    for rtline in "${ROUTE_UP[@]}"; do
      /sbin/route $rtline || stat_fail && exit 1
    done
    stat_done
    ;;
  stop)
    stat_busy "Stopping Network"
    for rtline in "${ROUTE_DN[@]}"; do
      /sbin/route $rtline || stat_fail && exit 1
    done
    for ifline in "${IF_DN[@]}"; do
      /sbin/ifconfig $ifline || stat_fail && exit 1
    done
    stat_done
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
